using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace LadybugDB.SourceGen;

/// <summary>Pure string emission: turns the resolved <see cref="RowModel"/> set into C# source.</summary>
internal static class Emitter
{
    public const string MapperClassName = "LadybugRowMappers";

    public static string Emit(ImmutableArray<RowModel> models)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace LadybugDB");
        sb.AppendLine("{");
        sb.AppendLine($"    public static partial class {MapperClassName}");
        sb.AppendLine("    {");

        // One generic entry point each for Map / MapAsync, dispatched at compile time on typeof(T).
        EmitMapDispatcher(sb, models);
        EmitMapAsyncDispatcher(sb, models);

        // Per-type, non-generic materializers (avoids CS0111 collisions between identical generic
        // signatures, and keeps each construction body concrete and reflection-free).
        foreach (RowModel model in models)
        {
            EmitTypeMappers(sb, model);
        }

        // One shared, case-insensitive column-name -> ordinal index builder for all mappers.
        EmitIndexBuilder(sb);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitMapDispatcher(StringBuilder sb, ImmutableArray<RowModel> models)
    {
        sb.AppendLine("        /// <summary>Materializes the result rows into <typeparamref name=\"T\"/> instances (reflection-free, AOT-safe).</summary>");
        sb.AppendLine("        public static System.Collections.Generic.IReadOnlyList<T> Map<T>(this global::LadybugDB.QueryResult result)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (result is null) throw new System.ArgumentNullException(nameof(result));");
        foreach (RowModel model in models)
        {
            sb.AppendLine($"            if (typeof(T) == typeof({model.TypeFullName})) return (System.Collections.Generic.IReadOnlyList<T>)(object){MapMethodName(model)}(result);");
        }

        sb.AppendLine("            throw new System.NotSupportedException(\"Type '\" + typeof(T).FullName + \"' is not a [LadybugRow] type in this compilation. Annotate it with [LadybugDB.LadybugRow].\");");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitMapAsyncDispatcher(StringBuilder sb, ImmutableArray<RowModel> models)
    {
        sb.AppendLine("        /// <summary>Streams the result rows as <typeparamref name=\"T\"/> instances (reflection-free, AOT-safe).</summary>");
        sb.AppendLine("        public static System.Collections.Generic.IAsyncEnumerable<T> MapAsync<T>(this global::LadybugDB.QueryResult result, System.Threading.CancellationToken ct = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (result is null) throw new System.ArgumentNullException(nameof(result));");
        foreach (RowModel model in models)
        {
            sb.AppendLine($"            if (typeof(T) == typeof({model.TypeFullName})) return (System.Collections.Generic.IAsyncEnumerable<T>)(object){MapAsyncMethodName(model)}(result, ct);");
        }

        sb.AppendLine("            throw new System.NotSupportedException(\"Type '\" + typeof(T).FullName + \"' is not a [LadybugRow] type in this compilation. Annotate it with [LadybugDB.LadybugRow].\");");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitTypeMappers(StringBuilder sb, RowModel model)
    {
        // Synchronous materializer.
        sb.AppendLine($"        private static System.Collections.Generic.IReadOnlyList<{model.TypeFullName}> {MapMethodName(model)}(global::LadybugDB.QueryResult result)");
        sb.AppendLine("        {");
        sb.AppendLine("            var __idx = BuildIndex(result.ColumnNames);");
        sb.AppendLine($"            var __list = new System.Collections.Generic.List<{model.TypeFullName}>();");
        sb.AppendLine("            foreach (var __row in result.Rows())");
        sb.AppendLine("            {");
        sb.AppendLine($"                __list.Add({BuildConstruction(model)});");
        sb.AppendLine("            }");
        sb.AppendLine("            return __list;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Asynchronous (streaming) materializer.
        sb.AppendLine($"        private static async System.Collections.Generic.IAsyncEnumerable<{model.TypeFullName}> {MapAsyncMethodName(model)}(global::LadybugDB.QueryResult result, [System.Runtime.CompilerServices.EnumeratorCancellation] System.Threading.CancellationToken ct)");
        sb.AppendLine("        {");
        sb.AppendLine("            var __idx = BuildIndex(result.ColumnNames);");
        sb.AppendLine("            foreach (var __row in result.Rows())");
        sb.AppendLine("            {");
        sb.AppendLine("                ct.ThrowIfCancellationRequested();");
        sb.AppendLine($"                yield return {BuildConstruction(model)};");
        sb.AppendLine("            }");
        sb.AppendLine("            await System.Threading.Tasks.Task.CompletedTask;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitIndexBuilder(StringBuilder sb)
    {
        sb.AppendLine("        private static System.Collections.Generic.Dictionary<string, int> BuildIndex(System.Collections.Generic.IReadOnlyList<string> cols)");
        sb.AppendLine("        {");
        sb.AppendLine("            var d = new System.Collections.Generic.Dictionary<string, int>(System.StringComparer.OrdinalIgnoreCase);");
        sb.AppendLine("            for (int i = 0; i < cols.Count; i++) d[cols[i]] = i;");
        sb.AppendLine("            return d;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static string BuildConstruction(RowModel model)
    {
        if (model.UsePositionalConstructor)
        {
            // Positional construction for records / declared ctors: ctor params in order.
            var ctorArgs = model.Members
                .Where(m => m.Kind == MemberKind.ConstructorParameter)
                .OrderBy(m => m.ConstructorOrdinal)
                .Select(Convert);
            return $"new {model.TypeFullName}({string.Join(", ", ctorArgs)})";
        }

        var inits = model.Members
            .Where(m => m.Kind == MemberKind.SettableProperty)
            .Select(m => $"{m.MemberName} = {Convert(m)}");
        return $"new {model.TypeFullName}() {{ {string.Join(", ", inits)} }}";
    }

    private static string Convert(RowMember m)
    {
        // Reflection-free conversion: index the row by the column ordinal, cast through the
        // binding's CLR result type. NULL flows through as default for the target type.
        string cell = $"__row[__idx[\"{m.ColumnName}\"]]";
        return $"global::LadybugDB.LadybugRowConvert.To<{m.TypeFullName}>({cell})";
    }

    private static string MapMethodName(RowModel model) => "Map_" + Mangle(model);

    private static string MapAsyncMethodName(RowModel model) => "MapAsync_" + Mangle(model);

    private static string Mangle(RowModel model)
    {
        // Stable, unique, identifier-safe suffix from the fully-qualified type name.
        var sb = new StringBuilder(model.TypeFullName.Length);
        foreach (char c in model.TypeFullName)
        {
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        }

        return sb.ToString();
    }
}
