using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace LadybugDB.SourceGen;

/// <summary>Pure string emission: turns the resolved <see cref="RowModel"/> set into C# source.</summary>
internal static class Emitter
{
    public const string MapperClassName = "LadybugRowMappers";

    public static string Emit(ImmutableArray<RowModel> models)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace LadybugDB");
        sb.AppendLine("{");
        sb.AppendLine($"    public static partial class {MapperClassName}");
        sb.AppendLine("    {");

        // One generic entry point each for Map / MapAsync, dispatched at compile time on typeof(T).
        EmitMapDispatcher(sb, models);
        EmitMapAsyncDispatcher(sb, models);

        // Per-type, non-generic materializers (avoids CS0111 collisions between identical generic
        // signatures, and keeps each construction body concrete and reflection-free).
        foreach (RowModel model in models)
        {
            EmitTypeMappers(sb, model);
        }

        // One shared, case-insensitive column-name -> ordinal index builder for all mappers.
        EmitIndexBuilder(sb);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitMapDispatcher(StringBuilder sb, ImmutableArray<RowModel> models)
    {
        sb.AppendLine("        /// <summary>Materializes the result rows into <typeparamref name=\"T\"/> instances (reflection-free, AOT-safe).</summary>");
        sb.AppendLine("        public static System.Collections.Generic.IReadOnlyList<T> Map<T>(this global::LadybugDB.QueryResult result)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (result is null) throw new System.ArgumentNullException(nameof(result));");
        foreach (RowModel model in models)
        {
            sb.AppendLine($"            if (typeof(T) == typeof({model.TypeFullName})) return (System.Collections.Generic.IReadOnlyList<T>)(object){MapMethodName(model)}(result);");
        }

        sb.AppendLine("            throw new System.NotSupportedException(\"Type '\" + typeof(T).FullName + \"' is not a [LadybugRow] type in this compilation. Annotate it with [LadybugDB.LadybugRow].\");");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitMapAsyncDispatcher(StringBuilder sb, ImmutableArray<RowModel> models)
    {
        sb.AppendLine("        /// <summary>Streams the result rows as <typeparamref name=\"T\"/> instances (reflection-free, AOT-safe).</summary>");
        sb.AppendLine("        public static System.Collections.Generic.IAsyncEnumerable<T> MapAsync<T>(this global::LadybugDB.QueryResult result, System.Threading.CancellationToken ct = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (result is null) throw new System.ArgumentNullException(nameof(result));");
        foreach (RowModel model in models)
        {
            sb.AppendLine($"            if (typeof(T) == typeof({model.TypeFullName})) return (System.Collections.Generic.IAsyncEnumerable<T>)(object){MapAsyncMethodName(model)}(result, ct);");
        }

        sb.AppendLine("            throw new System.NotSupportedException(\"Type '\" + typeof(T).FullName + \"' is not a [LadybugRow] type in this compilation. Annotate it with [LadybugDB.LadybugRow].\");");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitTypeMappers(StringBuilder sb, RowModel model)
    {
        // Synchronous materializer.
        sb.AppendLine($"        private static System.Collections.Generic.IReadOnlyList<{model.TypeFullName}> {MapMethodName(model)}(global::LadybugDB.QueryResult result)");
        sb.AppendLine("        {");
        sb.AppendLine("            var __idx = BuildIndex(result.ColumnNames);");
        sb.AppendLine("            int __capacity = result.RowCount > (ulong)int.MaxValue ? int.MaxValue : (int)result.RowCount;");
        sb.AppendLine($"            var __list = new System.Collections.Generic.List<{model.TypeFullName}>(__capacity);");
        if (CanEmitTypedAccessorPath(model))
        {
            sb.AppendLine($"            if ({CanUseTypedAccessorsMethodName(model)}(result.Columns, __idx))");
            sb.AppendLine("            {");
            EmitTypedAccessorIndexLocals(sb, model, indent: "                ");
            sb.AppendLine("                while (result.HasNext())");
            sb.AppendLine("                {");
            sb.AppendLine("                    using var __tuple = result.GetNext();");
            sb.AppendLine($"                    __list.Add({BuildConstruction(model, ConvertTypedTuple)});");
            sb.AppendLine("                }");
            sb.AppendLine("                return __list;");
            sb.AppendLine("            }");
        }

        sb.AppendLine("            foreach (var __row in result.Rows())");
        sb.AppendLine("            {");
        sb.AppendLine($"                __list.Add({BuildConstruction(model, ConvertMaterializedRow)});");
        sb.AppendLine("            }");
        sb.AppendLine("            return __list;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Asynchronous (streaming) materializer.
        sb.AppendLine($"        private static async System.Collections.Generic.IAsyncEnumerable<{model.TypeFullName}> {MapAsyncMethodName(model)}(global::LadybugDB.QueryResult result, [System.Runtime.CompilerServices.EnumeratorCancellation] System.Threading.CancellationToken ct)");
        sb.AppendLine("        {");
        sb.AppendLine("            var __idx = BuildIndex(result.ColumnNames);");
        if (CanEmitTypedAccessorPath(model))
        {
            sb.AppendLine($"            if ({CanUseTypedAccessorsMethodName(model)}(result.Columns, __idx))");
            sb.AppendLine("            {");
            EmitTypedAccessorIndexLocals(sb, model, indent: "                ");
            sb.AppendLine("                while (result.HasNext())");
            sb.AppendLine("                {");
            sb.AppendLine("                    ct.ThrowIfCancellationRequested();");
            sb.AppendLine("                    using var __tuple = result.GetNext();");
            sb.AppendLine($"                    yield return {BuildConstruction(model, ConvertTypedTuple)};");
            sb.AppendLine("                }");
            sb.AppendLine("                yield break;");
            sb.AppendLine("            }");
        }

        sb.AppendLine("            foreach (var __row in result.Rows())");
        sb.AppendLine("            {");
        sb.AppendLine("                ct.ThrowIfCancellationRequested();");
        sb.AppendLine($"                yield return {BuildConstruction(model, ConvertMaterializedRow)};");
        sb.AppendLine("            }");
        sb.AppendLine("            await System.Threading.Tasks.Task.CompletedTask;");
        sb.AppendLine("        }");
        sb.AppendLine();

        if (CanEmitTypedAccessorPath(model))
        {
            EmitTypedAccessorGuard(sb, model);
        }
    }

    private static void EmitIndexBuilder(StringBuilder sb)
    {
        sb.AppendLine("        private static System.Collections.Generic.Dictionary<string, int> BuildIndex(System.Collections.Generic.IReadOnlyList<string> cols)");
        sb.AppendLine("        {");
        sb.AppendLine("            var d = new System.Collections.Generic.Dictionary<string, int>(System.StringComparer.OrdinalIgnoreCase);");
        sb.AppendLine("            for (int i = 0; i < cols.Count; i++) d[cols[i]] = i;");
        sb.AppendLine("            return d;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitTypedAccessorIndexLocals(StringBuilder sb, RowModel model, string indent)
    {
        for (int i = 0; i < model.Members.Length; i++)
        {
            RowMember member = model.Members[i];
            sb.AppendLine($"{indent}int {TypedIndexLocalName(member, i)} = __idx[\"{member.ColumnName}\"];");
        }
    }

    private static string BuildConstruction(RowModel model, System.Func<RowMember, int, string> convert)
    {
        if (model.UsePositionalConstructor)
        {
            // Positional construction for records / declared ctors: ctor params in order.
            var ctorArgs = model.Members
                .Select((member, index) => (member, index))
                .Where(x => x.member.Kind == MemberKind.ConstructorParameter)
                .OrderBy(x => x.member.ConstructorOrdinal)
                .Select(x => convert(x.member, x.index));
            return $"new {model.TypeFullName}({string.Join(", ", ctorArgs)})";
        }

        var inits = model.Members
            .Select((member, index) => (member, index))
            .Where(x => x.member.Kind == MemberKind.SettableProperty)
            .Select(x => $"{x.member.MemberName} = {convert(x.member, x.index)}");
        return $"new {model.TypeFullName}() {{ {string.Join(", ", inits)} }}";
    }

    private static string ConvertMaterializedRow(RowMember m, int index)
    {
        // Reflection-free conversion: index the row by the column ordinal, cast through the
        // binding's CLR result type. NULL flows through as default for the target type.
        string cell = $"__row[__idx[\"{m.ColumnName}\"]]";
        return $"global::LadybugDB.LadybugRowConvert.To<{m.TypeFullName}>({cell})";
    }

    private static string ConvertTypedTuple(RowMember m, int index)
    {
        TypedAccessor accessor = GetTypedAccessor(m)!;
        string ordinal = TypedIndexLocalName(m, index);
        string expression = accessor.IsString
            ? $"__tuple.{accessor.ReadMethod}({ordinal})"
            : $"__tuple.{accessor.ReadMethod}({ordinal})";
        return accessor.IsString && !m.IsNullable ? expression + "!" : expression;
    }

    private static string TypedIndexLocalName(RowMember member, int index)
        => $"__{Mangle(member.ColumnName)}Index{index.ToString(System.Globalization.CultureInfo.InvariantCulture)}";

    private static void EmitTypedAccessorGuard(StringBuilder sb, RowModel model)
    {
        sb.AppendLine($"        private static bool {CanUseTypedAccessorsMethodName(model)}(System.Collections.Generic.IReadOnlyList<global::LadybugDB.ColumnSchema> columns, System.Collections.Generic.Dictionary<string, int> idx)");
        sb.AppendLine("        {");
        sb.AppendLine("            return");
        for (int i = 0; i < model.Members.Length; i++)
        {
            RowMember member = model.Members[i];
            TypedAccessor accessor = GetTypedAccessor(member)!;
            string suffix = i == model.Members.Length - 1 ? ";" : " &&";
            string indexName = $"__{Mangle(member.ColumnName)}Index{i.ToString(System.Globalization.CultureInfo.InvariantCulture)}";
            sb.AppendLine($"                idx.TryGetValue(\"{member.ColumnName}\", out int {indexName}) &&");
            sb.AppendLine($"                {BuildTypeCheck($"columns[{indexName}].Type.Id", accessor)}{suffix}");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static string BuildTypeCheck(string typeExpression, TypedAccessor accessor)
    {
        if (accessor.DataType == "Int64")
        {
            return $"({typeExpression} == global::LadybugDB.DataTypeId.Int64 || {typeExpression} == global::LadybugDB.DataTypeId.Serial)";
        }

        return $"{typeExpression} == global::LadybugDB.DataTypeId.{accessor.DataType}";
    }

    private static bool CanEmitTypedAccessorPath(RowModel model) =>
        model.Members.Length > 0 && model.Members.All(m => GetTypedAccessor(m) is not null);

    private static TypedAccessor? GetTypedAccessor(RowMember member)
    {
        // Nullable<T> still needs the materialized fallback so NULL maps to a nullable value rather
        // than the default underlying value. Nullable reference strings are safe.
        if (member.IsNullable && !IsString(member.TypeFullName))
        {
            return null;
        }

        string type = NormalizeType(member.TypeFullName);
        return type switch
        {
            "System.String" => new TypedAccessor("String", "GetString", IsString: true),
            "System.Boolean" => new TypedAccessor("Bool", "GetBoolOrDefault"),
            "System.SByte" => new TypedAccessor("Int8", "GetInt8OrDefault"),
            "System.Int16" => new TypedAccessor("Int16", "GetInt16OrDefault"),
            "System.Int32" => new TypedAccessor("Int32", "GetInt32OrDefault"),
            "System.Int64" => new TypedAccessor("Int64", "GetInt64OrDefault"),
            "System.Byte" => new TypedAccessor("UInt8", "GetUInt8OrDefault"),
            "System.UInt16" => new TypedAccessor("UInt16", "GetUInt16OrDefault"),
            "System.UInt32" => new TypedAccessor("UInt32", "GetUInt32OrDefault"),
            "System.UInt64" => new TypedAccessor("UInt64", "GetUInt64OrDefault"),
            "System.Single" => new TypedAccessor("Float", "GetFloatOrDefault"),
            "System.Double" => new TypedAccessor("Double", "GetDoubleOrDefault"),
            _ => null,
        };
    }

    private static bool IsString(string typeFullName) => NormalizeType(typeFullName) == "System.String";

    private static string NormalizeType(string typeFullName)
    {
        string type = typeFullName.StartsWith("global::", System.StringComparison.Ordinal)
            ? typeFullName.Substring("global::".Length)
            : typeFullName;

        return type switch
        {
            "string" => "System.String",
            "bool" => "System.Boolean",
            "sbyte" => "System.SByte",
            "short" => "System.Int16",
            "int" => "System.Int32",
            "long" => "System.Int64",
            "byte" => "System.Byte",
            "ushort" => "System.UInt16",
            "uint" => "System.UInt32",
            "ulong" => "System.UInt64",
            "float" => "System.Single",
            "double" => "System.Double",
            _ => type,
        };
    }

    private static string MapMethodName(RowModel model) => "Map_" + Mangle(model);

    private static string MapAsyncMethodName(RowModel model) => "MapAsync_" + Mangle(model);

    private static string CanUseTypedAccessorsMethodName(RowModel model) => "CanUseTypedAccessors_" + Mangle(model);

    private static string Mangle(RowModel model)
    {
        // Stable, unique, identifier-safe suffix from the fully-qualified type name.
        var sb = new StringBuilder(model.TypeFullName.Length);
        foreach (char c in model.TypeFullName)
        {
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        }

        return sb.ToString();
    }

    private static string Mangle(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (char c in value)
        {
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        }

        return sb.ToString();
    }

    private sealed record TypedAccessor(string DataType, string ReadMethod, bool IsString = false);
}
